### ISSUE TITLE
Lagassist Comand GUI Not working

### ISSUE THREAD

**Issue by mrshadow-in** [alvindimas05/LagAssist#1]
Server Type: Purpur
Version: 1.20.4
Java: 21

Console Spam: True
Console Log: https://mclo.gs/kd5wbtv

Issues:GUI Not working and Console Spam is separete

**Comment by alvindimas05** [comment]
Try the latest version and get the jar file based on your server version.

https://github.com/alvindimas05/LagAssist/releases/latest
