### ISSUE TITLE
Blank Lag Map

### ISSUE THREAD

**Issue by MadeBySaints** [alvindimas05/LagAssist#5]
fresh install on latest stable paper 1.21.1

No console error

Steps to reproduce:
1 /lagassist getmap
2 observe blank map

![{23C214E5-95A6-4F55-AC03-1C6245283F0C}](https://github.com/user-attachments/assets/484110cb-c8c9-47a0-8e5c-5528d725719a)

**Comment by DaveTheCamper** [comment]
To fix this issue, simply add a default MapView to the ItemStack; that will be enough to resolve the problem.

![image](https://github.com/user-attachments/assets/6070d070-907b-4a63-b172-b229062f574b)
![image](https://github.com/user-attachments/assets/da91647e-d8ea-4ef5-8d09-5dbc3e3070db)

**Comment by alvindimas05** [comment]
Fixed at 0011b05 (Thanks to @DaveTheCamper)
